"""baseline

Revision ID: 173e0e19449b
Revises: 
Create Date: 2025-12-30 16:08:46.750869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173e0e19449b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ms_teams_meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=256), nullable=True),
    sa.Column('meeting_id', sa.String(length=64), nullable=True),
    sa.Column('invite_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('city_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'city_id', name='uq_meeting_room_city')
    )
    op.create_index(op.f('ix_meeting_rooms_city_id'), 'meeting_rooms', ['city_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start_ts', sa.DateTime(), nullable=False),
    sa.Column('end_ts', sa.DateTime(), nullable=False),
    sa.Column('city_id', sa.String(length=36), nullable=True),
    sa.Column('meeting_room_id', sa.String(length=36), nullable=True),
    sa.Column('ms_teams_meeting_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['meeting_room_id'], ['meeting_rooms.id'], ),
    sa.ForeignKeyConstraint(['ms_teams_meeting_id'], ['ms_teams_meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_city_id'), 'meetings', ['city_id'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_room_id'), 'meetings', ['meeting_room_id'], unique=False)
    op.create_index(op.f('ix_meetings_ms_teams_meeting_id'), 'meetings', ['ms_teams_meeting_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), server_default='', nullable=False),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_device_fingerprint'), 'participants', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_participants_last_seen_at'), 'participants', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_participants_meeting_id'), 'participants', ['meeting_id'], unique=False)
    op.create_table('engagement_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('bucket', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'bucket', name='uq_sample_bucket')
    )
    op.create_index('ix_engagement_samples_bucket', 'engagement_samples', ['bucket'], unique=False)
    op.create_index('ix_engagement_samples_meeting_id', 'engagement_samples', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_engagement_samples_participant_id'), 'engagement_samples', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engagement_samples_participant_id'), table_name='engagement_samples')
    op.drop_index('ix_engagement_samples_meeting_id', table_name='engagement_samples')
    op.drop_index('ix_engagement_samples_bucket', table_name='engagement_samples')
    op.drop_table('engagement_samples')
    op.drop_index(op.f('ix_participants_meeting_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_last_seen_at'), table_name='participants')
    op.drop_index(op.f('ix_participants_device_fingerprint'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_meetings_ms_teams_meeting_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_room_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_city_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_meeting_rooms_city_id'), table_name='meeting_rooms')
    op.drop_table('meeting_rooms')
    op.drop_table('ms_teams_meetings')
    op.drop_table('cities')
    # ### end Alembic commands ###

